apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-netcore-demo-deployment
spec:
  selector:
    matchLabels:
      app: aks-netcore-demo-pod
  template:
    metadata:
      labels:
        app: aks-netcore-demo-pod
    spec:
      containers:
      - name: aks-netcore-demo-container
        image: ccr001.azurecr.io/aksnetcoredemo:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: http
