apiVersion: v1
kind: Service
metadata:
  name: aks-netcore-demo-service
spec:
  selector:
    app: aks-netcore-demo-pod
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 80
  type: LoadBalancer
